"""empty message

Revision ID: 4fa505b41078
Revises: 
Create Date: 2021-04-20 16:47:58.866157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa505b41078'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_confirmation', sa.Column('uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'email_confirmation', 'user', ['uid'], ['user_id'])
    op.add_column('listing', sa.Column('cid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'listing', 'category', ['cid'], ['category_id'])
    op.add_column('user', sa.Column('lid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'listing', ['lid'], ['listing_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'lid')
    op.drop_constraint(None, 'listing', type_='foreignkey')
    op.drop_column('listing', 'cid')
    op.drop_constraint(None, 'email_confirmation', type_='foreignkey')
    op.drop_column('email_confirmation', 'uid')
    # ### end Alembic commands ###
