"""empty message

Revision ID: c5949ea1a8ad
Revises: 4fa505b41078
Create Date: 2021-04-20 19:08:04.670857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5949ea1a8ad'
down_revision = '4fa505b41078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('time_of_creation', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'time_of_creation')
    # ### end Alembic commands ###
